### ISSUE TITLE
Grid works, no Drag and Drop...

### ISSUE THREAD

**Issue by JulianSwales** [DevOrbiter/drag_and_drop_gridview#1]
I've been attempting to give this library a shot to see if it will do what I want.. However it's not working... I'm assuming I'm dong something incorrect.. The following code builds the grid, but drag and drop does nothing and a long click on a tile crashed the code: 

```import 'package:intl/intl.dart';

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:drag_and_drop_gridview/devdrag.dart';

import 'package:golf_booking/blocs/bookings/bookings_bloc.dart';

import 'package:golf_booking/models/booking.dart';

class CalendarPage extends StatefulWidget {
  @override
  _CalendarPageState createState() => _CalendarPageState();
}

class _CalendarPageState extends State<CalendarPage> {
  List<Booking> _events;
  List<dynamic> _selectedEvents;
  List<String> _simulators;
  List<String> _timeSlots;
  List<String> _timeSlots24;

  DateFormat timeFormat = DateFormat("HH:mm");

  ScrollController _scrollController;

  @override
  void initState() {
    super.initState();

    _events = [];
    _selectedEvents = [];
    _simulators = [];
    _timeSlots = [];
    _timeSlots24 = [];
    BlocProvider.of<BookingsBloc>(context).add(
      LoadBookingTable(DateTime.now()),
    );
  }

  List<Booking> _groupEvents(Map<String, dynamic> bookingInfo) {
    print('bookingInfo: ${bookingInfo}');
    _simulators = bookingInfo['simulators'];
    print('_simulators: ${_simulators}');
    _timeSlots = bookingInfo['times'];
    print('_timeSlots: ${_timeSlots}');
    _timeSlots24 = bookingInfo['times24'];
    print('_timeSlots24: ${_timeSlots24}');

    final _slotTotal = _simulators.length * _timeSlots.length;
    print('_slotTotal: $_slotTotal');
    List<Booking> data = [];
    for (var i = 0; i < _slotTotal; i++) {
      final book = new Booking();
      data.add(book);
    }

    bookingInfo['bookings'].forEach((booking) {
      print('${booking.simulator}');
      final currsim =
          _simulators.indexWhere((element) => element == booking.simulator);
      print('currsim: $currsim');
      print('${booking.bookingStarttime}');
      final currstart = _timeSlots24
          .indexWhere((element) => element == booking.bookingStarttime);
      print('currstart: $currstart');
      final location = (currsim + 1) * (currstart + 1);
      data[location] = booking;
      //if (data[date] == null) data[date] = [];
      //data[date].add(event);
    });
    print(data);
    return data;
  }

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<BookingsBloc, BookingsState>(builder: (context, state) {
      if (state is BookingsLoading) {
        //return LoadingIndicator();
        return CircularProgressIndicator();
      } else if (state is BookingTableLoaded) {
        print('Empty: ${state.bookings}');
        if (state.bookings.isNotEmpty) {
          print('In dateformat');
          _events = _groupEvents(state.bookings);
        }
        return Center(
            child: DragAndDropGridView(
          controller: _scrollController,
          gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
              crossAxisCount: _simulators.length),
          padding: EdgeInsets.all(20),
          itemBuilder: (context, index) => Card(
            elevation: 2,
            child: LayoutBuilder(builder: (context, costrains) {
              return GridTile(
                child: Text(
                  '${_events[index].bookingStarttime}',
                  style: TextStyle(
                      backgroundColor:
                          _events[index].id != null ? Colors.yellow : null),
                ),
              );
            }),
          ),
          itemCount: _events.length,
          onWillAccept: (data) => true,
          onReorder: (oldIndex, newIndex) {
            print('In Reorder');
            final temp = _events[oldIndex];
            _events[oldIndex] = _events[newIndex];
            _events[newIndex] = temp;
            setState(() {});
          },
        ));
      } else {
        return Container();
      }
    });
  }
}
```

For now just outputting text, until I can see it working.. 

If I long press on a grid item it crashes: 

```═╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
Closure call with mismatched arguments: function '_CalendarPageState.build.<anonymous
closure>.<anonymous closure>'
Receiver: Closure: (dynamic) => bool
Tried calling: _CalendarPageState.build.<anonymous closure>.<anonymous closure>(34, 34)
Found: _CalendarPageState.build.<anonymous closure>.<anonymous closure>(dynamic) => bool
When the exception was thrown, this was the stack:
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)
#1      _DragAndDropGridViewState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> 
package:drag_and_drop_gridview/devdrag.dart:148
#2      _DragTargetState.didEnter 
package:flutter/…/widgets/drag_target.dart:553
#3      _DragAvatar.updateDrag.<anonymous closure> 
package:flutter/…/widgets/drag_target.dart:694
#4      ListMixin.firstWhere  (dart:collection/list.dart:142:15)
#5      _DragAvatar.updateDrag 
package:flutter/…/widgets/drag_target.dart:691
#6      new _DragAvatar 
package:flutter/…/widgets/drag_target.dart:627
#7      _DraggableState._startDrag 
package:flutter/…/widgets/drag_target.dart:388
#8      LongPressDraggable.createRecognizer.<anonymous closure> 
package:flutter/…/widgets/drag_target.dart:326
#9      MultiDragGestureRecognizer._startDrag.<anonymous closure> 
package:flutter/…/gestures/multidrag.dart:272
#10     GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:184
#11     MultiDragGestureRecognizer._startDrag 
package:flutter/…/gestures/multidrag.dart:272
#12     MultiDragGestureRecognizer.acceptGesture.<anonymous closure> 
package:flutter/…/gestures/multidrag.dart:262
#13     _DelayedPointerState.accepted 
package:flutter/…/gestures/multidrag.dart:491
#14     MultiDragGestureRecognizer.acceptGesture 
package:flutter/…/gestures/multidrag.dart:262
#15     GestureArenaManager._resolveInFavorOf 
package:flutter/…/gestures/arena.dart:265
#16     GestureArenaManager._resolve 
package:flutter/…/gestures/arena.dart:224
#17     GestureArenaEntry.resolve 
package:flutter/…/gestures/arena.dart:54
#18     MultiDragPointerState.resolve 
package:flutter/…/gestures/multidrag.dart:64
#19     _DelayedPointerState._delayPassed 
package:flutter/…/gestures/multidrag.dart:477
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
Handler: "onStart"```

Any thoughts on how I'm using this library incorrectly? 
Thanks.

**Comment by JulianSwales** [comment]
This line was the problem... 
          onWillAccept: (data) => true,
it should be 
          onWillAccept: (oldIndex, newIndex) => true,

This came from the pub.dev Readme... This example: 
"Below example shows you how to implement DragAndDropGridView easily." 

This should probably be fixed...

**Comment by DevOrbiter** [comment]
Thank you for reporting this issue. We updated our README.md.
